baseURL = "https://dauntlesswikijp.llism.net/"
languageCode = "ja"
defaultContentLanguage = "ja"
title = "Dauntless 日本語 Wiki"
hasCJKLanguage = true
enableEmoji = true
enableGitInfo = true

[blackfriday]
skipHTML = true
