baseURL = "https://dauntlesswikijp.llism.net/"
languageCode = "ja"
defaultContentLanguage = "ja"
title = "Dauntless日本語Wiki"
hasCJKLanguage = true
enableEmoji = true
enableGitInfo = true
googleAnalytics = "UA-131770768-2"

[blackfriday]
skipHTML = true
hardLineBreak = true
