backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "static"
public_folder: "/public"

collections:
  - label: "Page"
    name: "page"
    folder: "content/basic"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "公開日", name: "date", widget: "datetime"}
      - {label: "本文", name: "body", widget: "markdown"}
