backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "static/img"
public_folder: "/img"

collections:
  - label: "Basic"
    name: "basic"
    folder: "content/basic"
    create: true
    slug: "{{slug}}"
    preview_path: "/basic/{{slug}}"
    fields:
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "本文", name: "body", widget: "markdown"}
  - label: "Meta"
    name: "meta"
    folder: "content/meta"
    create: false
    slug: "{{slug}}"
    preview_path: "/meta/{{slug}}"
    fields:
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "本文", name: "body", widget: "markdown"}
