backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "static/img"
public_folder: "/img"

editor:
  preview: false

collections:
  - label: "Basic"
    name: "basic"
    folder: "content/basic"
    create: true
    slug: "{{slug}}"
    preview_path: "/basic/{{slug}}"
    fields:
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "本文", name: "body", widget: "markdown"}
  - label: "Data"
    name: "data"
    folder: "content/data"
    create: true
    slug: "{{slug}}"
    preview_path: "/data/{{slug}}"
    fields:
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "本文", name: "body", widget: "markdown"}
  - label: "Guide"
    name: "guide"
    folder: "content/guide"
    create: true
    slug: "{{slug}}"
    preview_path: "/guide/{{slug}}"
    fields:
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "本文", name: "body", widget: "markdown"}
  - label: "Meta"
    name: "meta"
    folder: "content/meta"
    create: false
    slug: "{{slug}}"
    preview_path: "/meta/{{slug}}"
    fields:
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "本文", name: "body", widget: "markdown"}
  - label: "Translate"
    name: "translate"
    folder: "content/translate"
    create: true
    slug: "{{slug}}"
    preview_path: "/translate/{{slug}}"
    fields:
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "本文", name: "body", widget: "markdown"}
  - label: "Translate/Patch"
    name: "translate-patch"
    folder: "content/translate/patch"
    create: true
    slug: "{{slug}}"
    preview_path: "/translate/patch/{{slug}}"
    fields:
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "本文", name: "body", widget: "markdown"}
  - label: "Translate/News"
    name: "translate-news"
    folder: "content/translate/news"
    create: true
    slug: "{{slug}}"
    preview_path: "/translate/news/{{slug}}"
    fields:
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "本文", name: "body", widget: "markdown"}
  - label: "Translate/Reddit"
    name: "translate-reddit"
    folder: "content/translate/reddit"
    create: true
    slug: "{{slug}}"
    preview_path: "/translate/reddit/{{slug}}"
    fields:
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "本文", name: "body", widget: "markdown"}
